language: node_js
node_js:
  - 0.8
  - 0.6

before_script:
  # Check the Postgres version
  - psql -c "SELECT version();" -U postgres
  # Create the user
  - psql -c "CREATE ROLE brmtest LOGIN ENCRYPTED PASSWORD 'md5a56ab74bbeb3854e09ea4e7df8d07650' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;" -U postgres
  # Create the database
  - psql -c 'CREATE DATABASE brmtest WITH OWNER brmtest;' -U postgres
  # Setup test tables
